package com.example.data.api

import com.squareup.moshi.JsonClass

// --- Generic Gemini API Models ---

@JsonClass(generateAdapter = true)
data class GenerateContentRequest(
    val contents: List<Content>,
    val generationConfig: GenerationConfig? = null,
    val systemInstruction: Content? = null
)

@JsonClass(generateAdapter = true)
data class Content(
    val parts: List<Part>
)

@JsonClass(generateAdapter = true)
data class Part(
    val text: String? = null
)

@JsonClass(generateAdapter = true)
data class GenerationConfig(
    val responseMimeType: String? = null,
    val temperature: Double? = null
)

@JsonClass(generateAdapter = true)
data class GenerateContentResponse(
    val candidates: List<Candidate>? = null
)

@JsonClass(generateAdapter = true)
data class Candidate(
    val content: Content? = null
)

// --- Custom Parsed Response Models (For deserializing JSON generated by Gemini) ---

@JsonClass(generateAdapter = true)
data class OnboardingAnalysisResponse(
    val activePathType: String,
    val activePathTitle: String,
    val scores: ScoresConfig,
    val opportunities: List<OpportunityItem>,
    val initialTasks: List<TaskItem>
)

@JsonClass(generateAdapter = true)
data class ScoresConfig(
    val direction: Int,
    val execution: Int,
    val income: Int,
    val consistency: Int,
    val skill: Int,
    val overall: Int
)

@JsonClass(generateAdapter = true)
data class OpportunityItem(
    val title: String,
    val term: String, // IMMEDIATE, MEDIUM, LONG
    val description: String,
    val potentialEarnings: String,
    val difficulty: String,
    val actionSteps: String
)

@JsonClass(generateAdapter = true)
data class TaskItem(
    val title: String,
    val description: String,
    val daysText: String,
    val proofRequired: String,
    val evidenceType: String,
    val verificationLevel: String // L1_SELF, L2_SCREENSHOT, L3_LINK, L4_REVENUE
)

@JsonClass(generateAdapter = true)
data class VerificationResponse(
    val approved: Boolean,
    val feedback: String,
    val incomeEarned: Double,
    val scoreAdjustments: ScoreAdjustments? = null
)

@JsonClass(generateAdapter = true)
data class ScoreAdjustments(
    val direction: Int,
    val execution: Int,
    val income: Int,
    val consistency: Int,
    val skill: Int,
    val overall: Int
)

@JsonClass(generateAdapter = true)
data class WeeklyReviewAdjustmentResponse(
    val scores: ScoresConfig,
    val advisoryFeedback: String,
    val adjustedTasks: List<TaskItem>? = null
)
